id: personal_information
title: Personal Information

questions:
  - id: name
    type: text
    label: "What is your name?"
    min_length: 10
    max_length: 100

  - id: have_alias
    type: boolean
    label: "Do you have an alias?"

  - id: alias
    type: text
    label: "What is your alias?"
    max_length: 200
    visible_if:
      value:
        question: have_alias
        equals: true

  - id: gender
    type: radio
    label: "What is your gender?"
    preset: genders

  - id: ethnicity
    type: checkbox
    label: "Select all that apply."
    preset: ethnicities
    allow_other: true
    allow_none: true