personal_information:
  name: "Ubba Huang"
  have_alias: true
  alias: "The U"
  gender: "male"
  ethnicity:
    - "asian"

about_the_situation:
  which_situation: "sa"
  live_in_us: false
  country: "ca"